Tried to create a new model for "new_rfp"
When I go and check the model in Rails Console I get an error message:

1.9.3-p392 :003 > New_rfp
RuntimeError: Circular dependency detected while autoloading constant
New_rfp
	from
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-4.0.0/lib/active_
support/dependencies.rb:460:in `load_missing_constant'
	from
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-4.0.0/lib/active_
support/dependencies.rb:183:in `const_missing'
	from (irb):3
	from
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-4.0.0/lib/rails/comman
ds/console.rb:90:in `start'
	from
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-4.0.0/lib/rails/comman
ds/console.rb:9:in `start'
	from
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-4.0.0/lib/rails/comman
ds.rb:64:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'